### ISSUE TITLE
Failed to activate the unity-dark-ui package

### ISSUE THREAD

**Issue by GiantRavens** [rschiang/unity-dark-ui#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [unity-dark-ui](https://github.com/rschiang/unity-dark-ui) package, v2.0.9
### Stack Trace

Failed to activate the unity-dark-ui package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/skip/.atom/packages/unity-dark-ui/lib/unity-ui.coffee:16:18
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
    at Object.module.exports.activate (/Users/skip/.atom/packages/unity-dark-ui/lib/unity-ui.coffee:12:19)
    at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:48:26
    at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:43:12)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:306:60
```
### Commands

```
     -0:54.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:50.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:49.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.2.0 settings-view:view-installed-packages (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".DS_Store",
      ".git",
      ".vagrant",
      "*.swp",
      ".localized"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "background-matrix",
      "deprecation-cop"
    ],
    "themes": [
      "unity-dark-ui",
      "atom-railscasts-syntax"
    ],
    "projectHome": "/Users/skip/Desktop/DEV/"
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.8
atom-railscasts-syntax, v1.0.6
compare-files, v0.4.1
highlight-line, v0.10.2
unity-dark-ui, v2.0.9

# Dev
No dev packages
```

**Comment by GiantRavens** [comment]
Problem appears to be other conflicting packages - pruned other packages, reinstalled ui theme and doesn't report error. Closing.
